import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import { ATCError, type ATCServices, eq, schema } from '@atc/core';

const execAsync = promisify(exec);

export interface DiscoveredInstance {
  serverUrl: string;
  port: number;
  pid: number | null;
  healthy: boolean;
  alreadyRegistered: boolean;
  existingAgentId: string | null;
  projectDirectory: string | null;
  sessionCount: number;
  busySessionCount: number;
}

export interface DetectedProcess {
  pid: number;
  command: string;
  hasHttpServer: boolean;
  extractedPort: number | null;
  listenPorts: number[];
}

export interface DiscoveryResult {
  discovered: DiscoveredInstance[];
  processes: DetectedProcess[];
  portsScanned: number;
  duration: number;
}

/**
 * PID-first discovery for running OpenCode instances.
 *
 * Detection flow:
 * 1. Process detection — OS-level process listing to find opencode binaries
 * 2. PID→Port mapping — OS network state (netstat/ss) to find actual listen ports
 * 3. Port probing — GET /global/health on PID-derived ports + priority port + existing agent URLs
 * 4. Enrichment — GET /path + /session/status on each discovered instance
 * 5. Reconciliation — re-associate agents whose port changed (session match → project dir match)
 * 6. Session assignment — group-based session→agent mapping with MCP cross-reference
 */

/** Check if an agent name is auto-generated (OpenCode@port or OpenCode-timestamp) */
function isAutoGeneratedName(name: string): boolean {
  return /^OpenCode[@-]/.test(name);
}

/** Session titles that represent the OpenCode default/greeting screen, not real work sessions */
const IGNORED_SESSION_TITLES = new Set(['Greeting']);

/** Check if a session title should be treated as a real work session */
function isWorkSession(title: string | undefined | null): boolean {
  return !!title && !IGNORED_SESSION_TITLES.has(title);
}
export class OpenCodeDiscovery {
  private services: ATCServices;

  /** Priority ports always included in scan (OpenCode serve default) */
  private static readonly PRIORITY_PORTS = [4096];

  constructor(services: ATCServices) {
    this.services = services;
  }

  /**
   * Scan for OpenCode instances using PID-first discovery.
   * No fixed port range — discovers ALL ports via OS process/network state.
   * Enriches each instance with project directory and session status.
   * Reconciles disconnected agents whose port has changed.
   */
  async scan(): Promise<DiscoveryResult> {
    const start = Date.now();

    // Get all existing OpenCode agents from DB for matching
    const existingAgents = this.services.db
      .select()
      .from(schema.agents)
      .where(eq(schema.agents.connectionType, 'opencode'))
      .all();

    const existingByUrl = new Map(
      existingAgents.filter((a) => a.serverUrl).map((a) => [a.serverUrl!, a.id]),
    );

    // Step 1: Detect processes + OS network state in parallel
    const [processes, listenMap] = await Promise.all([
      this.detectProcesses(),
      this.getListeningPortsMap(),
    ]);

    // Step 2: Enrich processes with actual listen ports from OS network state
    const pidPorts: number[] = [];
    for (const proc of processes) {
      proc.listenPorts = listenMap.get(proc.pid) ?? [];
      if (proc.listenPorts.length > 0) {
        proc.hasHttpServer = true;
      }
      pidPorts.push(...proc.listenPorts);
    }

    // Step 3: Build port list — PID-derived + priority + existing agent URLs (NO fixed range)
    const existingPorts = existingAgents
      .filter((a) => a.serverUrl)
      .map((a) => {
        try {
          return Number.parseInt(new URL(a.serverUrl!).port, 10);
        } catch {
          return 0;
        }
      })
      .filter((p) => p > 0);

    const allPorts = [
      ...new Set([...OpenCodeDiscovery.PRIORITY_PORTS, ...pidPorts, ...existingPorts]),
    ];

    // Skip the ATC server's own port
    const atcPort = Number.parseInt(process.env.PORT || '4000', 10);

    // Step 4: Probe all ports for OpenCode health endpoint
    const portResults = await Promise.allSettled(
      allPorts.filter((port) => port !== atcPort && port > 0).map((port) => this.probePort(port)),
    );

    const discovered: DiscoveredInstance[] = [];

    for (const result of portResults) {
      if (result.status === 'fulfilled' && result.value) {
        const { port, serverUrl } = result.value;
        const existingId = existingByUrl.get(serverUrl) ?? null;

        // Find PID for this port from OS network state
        const pid = this.findPidForPort(port, listenMap);

        discovered.push({
          serverUrl,
          port,
          pid,
          healthy: true,
          alreadyRegistered: existingId !== null,
          existingAgentId: existingId,
          projectDirectory: null,
          sessionCount: 0,
          busySessionCount: 0,
        });
      }
    }

    // Step 5: Enrich discovered instances with /path and /session/status data
    await Promise.allSettled(discovered.map((inst) => this.enrichInstance(inst)));

    // Step 6: Reconcile — re-associate disconnected agents whose port changed
    await this.reconcileAgents(discovered, existingAgents);

    // Step 6b: Update PID for existing agents from discovered instances
    for (const inst of discovered) {
      if (inst.existingAgentId && inst.pid != null) {
        const existingAgent = existingAgents.find((a) => a.id === inst.existingAgentId);
        if (existingAgent && existingAgent.processId !== inst.pid) {
          // PID changed or was null — update it in DB
          this.services.db
            .update(schema.agents)
            .set({ processId: inst.pid })
            .where(eq(schema.agents.id, inst.existingAgentId))
            .run();
        }
      }
    }

    // Step 7: Cross-reference — mark processes whose listen ports were discovered
    for (const proc of processes) {
      if (proc.listenPorts.some((p) => discovered.some((d) => d.port === p))) {
        proc.hasHttpServer = true;
      }
    }

    // Step 8: Group-based session assignment.
    // All OpenCode instances sharing the same CWD/project share a single session store.
    // We fetch the session list ONCE per CWD group, then assign unique sessions to each agent.
    const agentsWithUrl = existingAgents.filter((a) => a.serverUrl);
    if (agentsWithUrl.length > 0) {
      // Group agents by CWD (null CWD agents get their own group keyed by serverUrl)
      const cwdGroups = new Map<string, typeof agentsWithUrl>();
      for (const a of agentsWithUrl) {
        const groupKey = a.cwd ?? `__url__${a.serverUrl}`;
        const group = cwdGroups.get(groupKey) ?? [];
        group.push(a);
        cwdGroups.set(groupKey, group);
      }

      await Promise.allSettled(
        [...cwdGroups.values()].map(async (group) => {
          // Fetch CWD for agents missing it (use first agent's serverUrl)
          const representative = group[0];
          const sessions = await this.services.opencodeBridge.fetchAllSessions(
            representative.serverUrl!,
          );

          // Update CWD for any agents missing it
          for (const a of group) {
            if (!a.cwd && sessions.length > 0 && sessions[0].directory) {
              this.services.agentRegistry.updateSessionInfo(a.id, { cwd: sessions[0].directory });
              a.cwd = sessions[0].directory;
            }
          }

          if (sessions.length === 0) return;

          // Ignore untitled sessions (default screen) for tracking/assignment
          const titledSessions = sessions.filter((s) => s.id && isWorkSession(s.title));
          if (titledSessions.length === 0) return;

          // Build a set of session IDs already assigned within this group
          const assignedSessionIds = new Set<string>();
          for (const a of group) {
            if (a.sessionId && titledSessions.some((s) => s.id === a.sessionId)) {
              assignedSessionIds.add(a.sessionId);
            }
          }

          // Assign unassigned sessions to agents that don't have a valid one
          const unassignedSessions = titledSessions.filter((s) => !assignedSessionIds.has(s.id));
          let nextIdx = 0;

          // Track which session title was assigned to each agent (for auto-rename below)
          const agentSessionTitles = new Map<string, string>();

          for (const a of group) {
            const hasValidSession = a.sessionId && titledSessions.some((s) => s.id === a.sessionId);
            if (hasValidSession) {
              // Agent already has a valid session — just update the title in case it changed
              const session = titledSessions.find((s) => s.id === a.sessionId);
              if (session) {
                if (session.title !== a.sessionTitle) {
                  this.services.agentRegistry.updateSessionInfo(a.id, {
                    sessionId: a.sessionId,
                    sessionTitle: session.title,
                  });
                }
                if (session.title) agentSessionTitles.set(a.id, session.title);
              }
            } else if (a.sessionId && !titledSessions.some((s) => s.id === a.sessionId)) {
              // Agent's session no longer exists in the instance — disconnect as stale ghost
              await this.services.agentRegistry.disconnectById(a.id, 'session_vanished');
              continue;
            } else if (nextIdx < unassignedSessions.length) {
              // Assign the next available unassigned session
              const session = unassignedSessions[nextIdx++];
              this.services.agentRegistry.updateSessionInfo(a.id, {
                sessionId: session.id,
                sessionTitle: session.title,
              });
              if (session.title) agentSessionTitles.set(a.id, session.title);
            }
          }

          // Cross-reference with MCP-registered agents for trusted name and role.
          // MCP agents register with explicit name/role via register_agent tool —
          // these are more trustworthy than session titles.
          const mcpAgents = this.services.db
            .select()
            .from(schema.agents)
            .where(eq(schema.agents.connectionType, 'mcp'))
            .all();
          const mcpBySessionId = new Map(
            mcpAgents.filter((a) => a.sessionId).map((a) => [a.sessionId!, a]),
          );

          // Auto-rename and role-sync for discovery agents with generic names
          for (const a of group) {
            // Re-read the agent's current sessionId (may have been updated above)
            const currentAgent = this.services.agentRegistry.getById(a.id);
            const mcpMatch = currentAgent.sessionId
              ? mcpBySessionId.get(currentAgent.sessionId)
              : undefined;

            if (mcpMatch && mcpMatch.id !== a.id) {
              // Discovery agent duplicates MCP agent for the same session: merge into MCP row.
              await this.services.agentRegistry.reconnectOpenCodeAgent(mcpMatch.id, a.serverUrl!, {
                cwd: a.cwd ?? undefined,
                processId: a.processId ?? undefined,
              });
              await this.services.agentRegistry.removeById(a.id);
              continue;
            }

            if (mcpMatch) {
              // MCP agent found — use its name and role as primary source of truth
              if (isAutoGeneratedName(a.name) || a.name !== mcpMatch.name) {
                await this.services.agentRegistry.renameAgent(a.id, mcpMatch.name);
              }
              if (currentAgent.role !== mcpMatch.role) {
                await this.services.agentRegistry.updateRole(
                  a.id,
                  mcpMatch.role as 'main' | 'worker',
                );
              }
            } else {
              // No MCP match — fall back to session title
              const title = agentSessionTitles.get(a.id);
              if (title && isAutoGeneratedName(a.name)) {
                await this.services.agentRegistry.renameAgent(a.id, title);
              }

              // Title-based role reconnection from historical disconnected agents
              if (title) {
                const historicalMatch = this.services.db
                  .select()
                  .from(schema.agents)
                  .where(eq(schema.agents.sessionTitle, title))
                  .all()
                  .find((agent) => agent.id !== a.id && agent.status === 'disconnected');

                if (historicalMatch && currentAgent.role !== historicalMatch.role) {
                  await this.services.agentRegistry.updateRole(
                    a.id,
                    historicalMatch.role as 'main' | 'worker',
                  );
                }
              }
            }
          }
        }),
      );
    }

    return {
      discovered,
      processes,
      portsScanned: allPorts.length,
      duration: Date.now() - start,
    };
  }

  /**
   * Find the PID associated with a given port from OS network state.
   */
  private findPidForPort(port: number, listenMap: Map<number, number[]>): number | null {
    for (const [pid, ports] of listenMap) {
      if (ports.includes(port)) return pid;
    }
    return null;
  }

  /**
   * Enrich a discovered instance with project directory and session status data.
   * Calls GET /path and GET /session/status on the instance in parallel.
   */
  private async enrichInstance(instance: DiscoveredInstance): Promise<void> {
    const [pathInfo, statuses, sessions] = await Promise.all([
      this.services.opencodeBridge.fetchInstancePath(instance.serverUrl),
      this.services.opencodeBridge.fetchSessionStatuses(instance.serverUrl),
      this.services.opencodeBridge.fetchAllSessions(instance.serverUrl),
    ]);

    if (pathInfo) {
      instance.projectDirectory = pathInfo.directory || null;
    }

    instance.sessionCount = sessions.length;
    const busyCount = Object.values(statuses).filter((s) => s.type === 'busy').length;
    instance.busySessionCount = busyCount;
  }

  /**
   * Reconcile discovered instances with existing agents.
   * Handles port changes by re-associating agents to new URLs.
   *
   * Matching hierarchy (strongest → weakest):
   * 1. Exact serverUrl match → already registered (handled before this step)
   * 2. Session ID match → agent's session found on instance → reconnect
   * 3. Same project directory + disconnected agent → reconnect (weakest, disconnected only)
   */
  private async reconcileAgents(
    discovered: DiscoveredInstance[],
    existingAgents: Array<{
      id: string;
      serverUrl: string | null;
      sessionId: string | null;
      status: string;
      cwd: string | null;
    }>,
  ): Promise<void> {
    const unmatched = discovered.filter((d) => !d.alreadyRegistered);
    if (unmatched.length === 0) return;

    for (const instance of unmatched) {
      // Try session ID match: fetch instance sessions and check against agent sessionIds
      const sessions = await this.services.opencodeBridge.fetchAllSessions(instance.serverUrl);
      const instanceSessionIds = new Set(sessions.map((s) => s.id));

      // Find an existing agent whose sessionId appears in this instance's sessions
      const sessionMatch = existingAgents.find(
        (a) =>
          a.sessionId &&
          instanceSessionIds.has(a.sessionId) &&
          !this.isAlreadyMatched(a.id, discovered),
      );

      if (sessionMatch) {
        // Strong match: session ID links this instance to an existing agent
        await this.services.agentRegistry.reconnectOpenCodeAgent(
          sessionMatch.id,
          instance.serverUrl,
          {
            cwd: instance.projectDirectory ?? undefined,
            processId: instance.pid ?? undefined,
          },
        );
        instance.alreadyRegistered = true;
        instance.existingAgentId = sessionMatch.id;
        continue;
      }

      // Try project directory match for disconnected agents only (weakest signal)
      if (instance.projectDirectory) {
        const dirMatch = existingAgents.find(
          (a) =>
            a.status === 'disconnected' &&
            a.cwd === instance.projectDirectory &&
            !this.isAlreadyMatched(a.id, discovered),
        );

        if (dirMatch) {
          // Weaker match: same project directory + agent was disconnected
          await this.services.agentRegistry.reconnectOpenCodeAgent(
            dirMatch.id,
            instance.serverUrl,
            {
              cwd: instance.projectDirectory,
              processId: instance.pid ?? undefined,
            },
          );
          instance.alreadyRegistered = true;
          instance.existingAgentId = dirMatch.id;
          continue;
        }
      }
    }
  }

  /**
   * Check if an agent ID is already matched to a discovered instance.
   */
  private isAlreadyMatched(agentId: string, discovered: DiscoveredInstance[]): boolean {
    return discovered.some((d) => d.existingAgentId === agentId);
  }

  /**
   * Probe a single port for an OpenCode health endpoint.
   * Returns null if port is not an OpenCode instance.
   */
  private async probePort(port: number): Promise<{ port: number; serverUrl: string } | null> {
    const serverUrl = `http://127.0.0.1:${port}`;

    try {
      const res = await fetch(`${serverUrl}/global/health`, {
        signal: AbortSignal.timeout(500),
      });

      if (res.ok) {
        return { port, serverUrl };
      }
    } catch {
      // ECONNREFUSED, timeout, etc. — not an OpenCode instance
    }

    return null;
  }

  /**
   * Detect running OpenCode processes using OS-level process listing.
   * Filters out LSP subprocesses to return only actual OpenCode instances.
   */
  private async detectProcesses(): Promise<DetectedProcess[]> {
    try {
      if (process.platform === 'win32') {
        return await this.detectProcessesWin32();
      }
      return await this.detectProcessesUnix();
    } catch {
      return [];
    }
  }

  /**
   * Windows: Use wmic to find opencode.exe processes.
   */
  private async detectProcessesWin32(): Promise<DetectedProcess[]> {
    try {
      const { stdout } = await execAsync(
        'wmic process where "name=\'opencode.exe\'" get processid,commandline /format:list',
        { timeout: 5000 },
      );

      const processes: DetectedProcess[] = [];
      // wmic /format:list separates records by blank lines
      const blocks = stdout.split(/\r?\n\s*\r?\n/).filter((b) => b.trim());

      for (const block of blocks) {
        const lines = block.split(/\r?\n/).filter((l) => l.trim());
        let commandLine = '';
        let pid = 0;

        for (const line of lines) {
          const eqIdx = line.indexOf('=');
          if (eqIdx === -1) continue;
          const key = line.substring(0, eqIdx).trim();
          const value = line.substring(eqIdx + 1).trim();

          if (key === 'CommandLine') commandLine = value;
          else if (key === 'ProcessId') pid = Number.parseInt(value, 10);
        }

        if (!pid || Number.isNaN(pid)) continue;

        // Skip LSP/language-server subprocesses
        if (
          commandLine.includes('typescript-language-server') ||
          commandLine.includes('language-server --stdio')
        ) {
          continue;
        }

        const portMatch = commandLine.match(/--port\s+(\d+)/);
        const extractedPort = portMatch ? Number.parseInt(portMatch[1], 10) : null;
        const hasServeFlag = commandLine.includes(' serve') || extractedPort !== null;

        processes.push({
          pid,
          command: commandLine,
          hasHttpServer: hasServeFlag,
          extractedPort,
          listenPorts: [],
        });
      }

      return processes;
    } catch {
      return [];
    }
  }

  /**
   * Unix/macOS: Use ps to find opencode processes.
   */
  private async detectProcessesUnix(): Promise<DetectedProcess[]> {
    try {
      const { stdout } = await execAsync('ps -eo pid,args', { timeout: 5000 });
      const processes: DetectedProcess[] = [];

      for (const line of stdout.split('\n')) {
        const trimmed = line.trim();
        if (!trimmed.includes('opencode') || trimmed.includes('grep')) continue;

        const match = trimmed.match(/^(\d+)\s+(.+)$/);
        if (!match) continue;

        const pid = Number.parseInt(match[1], 10);
        const command = match[2];

        // Skip LSP subprocesses
        if (
          command.includes('typescript-language-server') ||
          command.includes('language-server --stdio')
        ) {
          continue;
        }

        const portMatch = command.match(/--port\s+(\d+)/);
        const extractedPort = portMatch ? Number.parseInt(portMatch[1], 10) : null;
        const hasServeFlag = command.includes(' serve') || extractedPort !== null;

        processes.push({
          pid,
          command,
          hasHttpServer: hasServeFlag,
          extractedPort,
          listenPorts: [],
        });
      }

      return processes;
    } catch {
      return [];
    }
  }

  /**
   * Get all listening TCP ports grouped by PID using OS network inspection.
   * Returns Map<PID, [ports]> for cross-referencing with detected processes.
   */
  private async getListeningPortsMap(): Promise<Map<number, number[]>> {
    try {
      if (process.platform === 'win32') {
        return await this.getListeningPortsMapWin32();
      }
      return await this.getListeningPortsMapUnix();
    } catch {
      return new Map();
    }
  }

  /**
   * Windows: Parse `netstat -ano` for LISTENING TCP connections.
   */
  private async getListeningPortsMapWin32(): Promise<Map<number, number[]>> {
    const { stdout } = await execAsync('netstat -ano', { timeout: 5000 });
    const map = new Map<number, number[]>();

    for (const line of stdout.split('\n')) {
      // Format: TCP    127.0.0.1:4096    0.0.0.0:0    LISTENING    36712
      const match = line.trim().match(/TCP\s+\S+:(\d+)\s+\S+\s+LISTENING\s+(\d+)/i);
      if (match) {
        const port = Number.parseInt(match[1], 10);
        const pid = Number.parseInt(match[2], 10);
        if (!map.has(pid)) map.set(pid, []);
        map.get(pid)!.push(port);
      }
    }

    return map;
  }

  /**
   * Unix/macOS: Parse `ss -tlnp` (Linux) or `lsof` (macOS) for listening ports.
   */
  private async getListeningPortsMapUnix(): Promise<Map<number, number[]>> {
    const map = new Map<number, number[]>();

    // Try ss first (standard on Linux)
    try {
      const { stdout } = await execAsync('ss -tlnp 2>/dev/null', { timeout: 5000 });

      for (const line of stdout.split('\n')) {
        // Format: LISTEN 0 128 127.0.0.1:4096 0.0.0.0:* users:(("opencode",pid=36712,fd=7))
        const portMatch = line.match(/:(\d+)\s/);
        const pidMatch = line.match(/pid=(\d+)/);
        if (portMatch && pidMatch) {
          const port = Number.parseInt(portMatch[1], 10);
          const pid = Number.parseInt(pidMatch[1], 10);
          if (!map.has(pid)) map.set(pid, []);
          map.get(pid)!.push(port);
        }
      }

      if (map.size > 0) return map;
    } catch {
      // ss not available — try lsof
    }

    // Fallback: lsof (macOS + Linux)
    try {
      const { stdout } = await execAsync('lsof -iTCP -sTCP:LISTEN -n -P 2>/dev/null', {
        timeout: 5000,
      });

      for (const line of stdout.split('\n')) {
        // Format: opencode 36712 user 7u IPv4 0x1234 0t0 TCP 127.0.0.1:4096 (LISTEN)
        const parts = line.trim().split(/\s+/);
        if (parts.length < 9 || parts[parts.length - 1] !== '(LISTEN)') continue;

        const pid = Number.parseInt(parts[1], 10);
        const namePort = parts[parts.length - 2];
        const portStr = namePort.split(':').pop();
        if (!portStr || Number.isNaN(pid)) continue;

        const port = Number.parseInt(portStr, 10);
        if (Number.isNaN(port)) continue;

        if (!map.has(pid)) map.set(pid, []);
        map.get(pid)!.push(port);
      }
    } catch {
      // No network inspection available
    }

    return map;
  }

  /**
   * Resolve the OS process ID (PID) for a given server URL by inspecting network state.
   * Parses the port from the URL, then cross-references with OS netstat/ss output.
   */
  async resolvePidForUrl(serverUrl: string): Promise<number | null> {
    try {
      const port = Number.parseInt(new URL(serverUrl).port, 10);
      if (!port || Number.isNaN(port)) return null;
      const listenMap = await this.getListeningPortsMap();
      return this.findPidForPort(port, listenMap);
    } catch {
      return null;
    }
  }

  /**
   * Track a discovered instance by registering it as an OpenCode agent.
   */
  async track(serverUrl: string, name?: string): Promise<{ agentId: string }> {
    const sessions = await this.services.opencodeBridge.fetchAllSessions(serverUrl);
    const titledSessions = sessions.filter((s) => s.id && isWorkSession(s.title));
    if (titledSessions.length === 0) {
      throw new ATCError(
        'TRACK_REQUIRES_TITLED_SESSION',
        'No titled session found; refusing to track default/untitled session state',
        400,
      );
    }

    const cwd = titledSessions[0].directory ?? null;

    // Group-aware session assignment: find sessions already used by agents with same CWD
    let assignedSession: (typeof titledSessions)[number] | undefined;
    const existingAgents = this.services.db
      .select()
      .from(schema.agents)
      .where(eq(schema.agents.connectionType, 'opencode'))
      .all();

    const sameGroupAgents = existingAgents.filter((a) => a.cwd === cwd);
    const assignedSessionIds = new Set(
      sameGroupAgents
        .filter((a) => a.sessionId && titledSessions.some((s) => s.id === a.sessionId))
        .map((a) => a.sessionId!),
    );

    assignedSession = titledSessions.find((s) => !assignedSessionIds.has(s.id)) ?? undefined;

    // Determine agent name: explicit name > MCP agent name > session title > generic fallback
    // Also cross-reference MCP-registered agents for trusted name and role
    const mcpAgents = assignedSession
      ? this.services.db
          .select()
          .from(schema.agents)
          .where(eq(schema.agents.connectionType, 'mcp'))
          .all()
      : [];
    const mcpMatch = assignedSession
      ? mcpAgents.find((a) => a.sessionId === assignedSession!.id)
      : undefined;

    const agentName =
      name || mcpMatch?.name || assignedSession?.title || `OpenCode@${new URL(serverUrl).port}`;

    // Resolve PID for this serverUrl via OS network state
    const pid = await this.resolvePidForUrl(serverUrl);

    const agent = await this.services.agentRegistry.registerOpenCodeAgent({
      name: agentName,
      serverUrl,
      ...(cwd ? { cwd } : {}),
      ...(pid != null ? { processId: pid } : {}),
    });

    // Store session assignment and sync MCP agent data
    if (assignedSession) {
      this.services.agentRegistry.updateSessionInfo(agent.id, {
        sessionId: assignedSession.id,
        sessionTitle: assignedSession.title,
      });

      if (mcpMatch) {
        // Sync role from MCP agent (most trusted source)
        if (agent.role !== mcpMatch.role) {
          await this.services.agentRegistry.updateRole(
            agent.id,
            mcpMatch.role as 'main' | 'worker',
          );
        }
      }
    }

    // Auto-register workspace from agent's CWD if it's a git repo
    if (cwd) {
      try {
        await this.services.workspaceService.createWorkspace({
          repoRoot: cwd,
          baseBranch: 'main',
        });
      } catch {
        // Workspace may already exist — ignore duplicate errors
      }
    }

    return { agentId: agent.id };
  }
}
